import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/SessionProvider";
import { NextThemeProvider } from "@/lib/NextThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <NextThemeProvider>
        {children}
        </NextThemeProvider>
        </AuthProvider>
        </body>
    </html>
  );
}
